version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'postgres_db'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shopping-cart-ms-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080

volumes:
  pg-data: